### ISSUE TITLE
#3: HIV prevalence by PSNU difficult to read in OUs with a lot of PSNUs

### ISSUE THREAD

**Issue by karishmas26** [USAID-OHA-SI/hardapoart#54]
![image](https://user-images.githubusercontent.com/84093378/218547545-6a4baa80-03ce-400d-a6ed-df8e98def71c.png)

**Comment by baboyma** [comment]
This was expected. The plan is to facet wrap or show only psnu with issues. Any other thoughts?

**Comment by achafetz** [comment]
Check out linkage - if there were more than 20 rows, I `slice_max()` by HTS_TST_POS (and then noted it in the caption). So here you could do the same thing, take the top PLHIV or prevalence psnus

https://github.com/USAID-OHA-SI/hardapoart/blob/564895e60e6301e16ccc225348986a67b285cea1/Scripts/06_Linkage_PSNU.R#L103-L107

**Comment by baboyma** [comment]
HIV Prev - limit # of records on visuals. max = 21 + country reference line
